# Generated by Django 2.2.2 on 2019-06-25 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization_name_variable', models.CharField(max_length=200)),
                ('localization_description_variable', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
                ('unique_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality', models.PositiveSmallIntegerField()),
                ('sell_price_min', models.BigIntegerField()),
                ('sell_price_min_date', models.DateTimeField()),
                ('sell_price_max', models.BigIntegerField()),
                ('sell_price_max_date', models.DateTimeField()),
                ('buy_price_min', models.BigIntegerField()),
                ('buy_price_min_date', models.DateTimeField()),
                ('buy_price_max', models.BigIntegerField()),
                ('buy_price_max_date', models.DateTimeField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.City')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Good')),
            ],
        ),
    ]
