# Generated by Django 2.2.2 on 2019-06-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='item_id',
            new_name='unique_name',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='item_id',
            new_name='good_id',
        ),
    ]
